### ISSUE TITLE
System.TypeInitializationException on Windows Phone 8

### ISSUE THREAD

**Issue by elpendor** [reactiveui/Akavache#348]
I'm getting the following exception:

```
Failed to initialize Akavache properly. Do you have a reference to Akavache.dll?

The type initializer for 'Akavache.BlobCache' threw an exception.

Stacktrace:
   at Akavache.Sqlite3.Registrations.Register(IMutableDependencyResolver resolver)
   at Akavache.DependencyResolverMixin.InitializeAkavache(IMutableDependencyResolver This)
   at Akavache.BlobCache.<>c.<.cctor>b__1_0()
   at Splat.Locator.RegisterResolverCallbackChanged(Action callback)
   at Akavache.BlobCache..cctor()
```

I have an MVVMCross project, Akavache 5.0.0 is installed on both the PCL and the WP project.  Both projects also have sqlite-net-pcl 1.3.1. The WP project is set to x86 when using the emulator.

Tried updating Splat but I can't get past 1.6.2.

Any ideas? Same code seems to be working with Akavache 4.1.2

**Comment by castrojr913** [comment]
The same thing with PCL Project, referencing to Xamarin.iOS :(
