### ISSUE TITLE
Linker problem in Android after migrating from packages.config

### ISSUE THREAD

**Issue by EmilAlipiev** [reactiveui/Akavache#408]
I am using version 6 and it was working fine without any special linker set up although i am using full linking but I migrated from packages.config to project references and suddenly this error popped up.
it looks like System.Reactive references are failing. using no linker works fine. Anybody has any idea what might cause this problem?

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		The "LinkAssemblies" task failed unexpectedly.
Mono.Linker.MarkException: Error processing method: 'System.Void System.StreamMixins/<>c__DisplayClass0_0::<WriteAsyncRx>b__0(System.IAsyncResult)'
 in assembly: 'Akavache.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Reactive.Subjects.SubjectBase`1
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
   at MonoDroid.Tuner.MonoDroidMarkStep.MarkType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()		
```

**Comment by PureWeen** [comment]
Honestly 
PackageRef + Linker => Still has issues
Which is more a .net tooling issue and not something I can easily resolve

I have this
```
	<assembly fullname="Akavache">
		<type fullname="*" />
	</assembly>
	<assembly fullname="Akavache.Sqlite3">
		<type fullname="*" />
	</assembly>
```
In my linker.xml file I use which seems to work fine with full linking...

**Comment by EmilAlipiev** [comment]
@PureWeen I also have same exactly, not in the xml file but on the settings tab as coma seperated like shown below. that is just working fine for me but as I said once I migrated from packages.config to project references, I am suddently getting this build error message. whatever I tried, I couldnt get rid of this message. 

![image](https://user-images.githubusercontent.com/10422347/40283509-764a40b6-5c7f-11e8-8ccb-3e26c27f4669.png)

**Comment by swapnil591** [comment]
Any solution

**Comment by swapnil591** [comment]
Mono.Linker.MarkException: Error processing method: 'System.Void Akavache.IsolatedStorageProvider

**Comment by glennawatson** [comment]
Thank you for your report. Closing as this is no longer applicable to Akavache V11.

V11 uses SDK-style projects with `PackageReference` exclusively — there is no `packages.config` to migrate from. The old linker issues with `System.Reactive` assembly resolution have been resolved by V11's modern project structure and updated dependency chain.

V11 also handles linker/trimmer concerns via `[Preserve]` attributes and `IsAotCompatible = true` rather than relying on linker configuration files.

If you encounter linker issues with V11, please open a new issue.
