### ISSUE TITLE
Linking error

### ISSUE THREAD

**Issue by swapnil591** [reactiveui/Akavache#461]
Severity	Code	Description	Project	File	Line	Suppression State
Error		The "LinkAssemblies" task failed unexpectedly.
Mono.Linker.MarkException: Error processing method: 'System.Void Akavache.IsolatedStorageProvider/<>c__DisplayClass2_0::<CreateRecursive>b__0()' in assembly: 'Akavache.Core.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.String[] System.String::Split(System.Char,System.StringSplitOptions)
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	DhruvTL.Android

**Comment by softlion** [comment]
Upgrade your SDK

**Comment by thisisthekap** [comment]
@softlion What should be upgraded in particular?

**Comment by softlion** [comment]
Xamarin.iOS and Xamarin.Android (it comes with visual studio updates). Or on appcenter in the build config.

**Comment by swapnil591** [comment]
still not working.

Mono.Linker.MarkException: Error processing method: 'System.Void Akavache.IsolatedStorageProvider/<>c__DisplayClass2_0::<CreateRecursive>b__0()' in assembly: 'Akavache.Core.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.String[] System.String::Split(System.Char,System.StringSplitOptions)

**Comment by glennawatson** [comment]
That one makes more sense, given Split(char) is a .Net Core only version of the Split method.

**Comment by yosel-vera** [comment]
I have the same issue, i can't generate my app because this error. This only happen in release mode.

**Comment by glennawatson** [comment]
I am hoping this issue will resolve once https://github.com/reactiveui/Akavache/pull/472 is merged.

**Comment by mkieres** [comment]
I just tried running iOS release build with latest 6.5.1 and I ran into the same problem as before:

> MTOUCH : error MT2101: Can't resolve the reference 'System.String[] System.String::Split(System.Char,System.StringSplitOptions)', referenced from the method 'System.Void Akavache.IsolatedStorageProvider/<>c__DisplayClass2_0::<CreateRecursive>b__0()' in 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'

**Comment by modplug** [comment]
As a workaround I inserted this snippet in my build pipeline:

```
echo 'Selecting Mono version...'
/bin/bash -c "sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 5_16_0"
```

**Comment by glennawatson** [comment]
@modplug fixes it for me also. Closing the issue.
