### ISSUE TITLE
[Bug]: Xamarin.Forms v9.1.7 crashing UWP with the exception UnauthorizedAccessException Access to the path 'C:\Users' is denied.

### ISSUE THREAD

**Issue by EmilAlipiev** [reactiveui/Akavache#850]
### Describe the bug 🐞

I have just upgraded on latest version v9.1.7 and UWP is crashing on BlobCache.UserAccount after initializing it  when initialize Akavache and try to make a call. It works fine on earlier versions

```
System.UnauthorizedAccessException
  HResult=0x80070005
  Message=Access to the path 'C:\Users' is denied.
  Source=System.IO.FileSystem
  StackTrace:
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Akavache.Utility.<>c.<CreateRecursive>b__2_0(String parent, String dir)
   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)
   at Akavache.Utility.CreateRecursive(DirectoryInfo directoryInfo)
   at Akavache.SimpleFilesystemProvider.CreateRecursive(String path)
   at Akavache.Sqlite3.Registrations.<>c__DisplayClass1_0.<Register>b__2()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.Lazy`1.CreateValue()
   at Splat.ModernDependencyResolver.GetService(Type serviceType, String contract)
   at Splat.DependencyResolverMixins.GetService[T](IReadonlyDependencyResolver resolver, String contract)
```
 

### Step to reproduce

1. Create Xamarin.Forms Project and start UWP project locally
2. Initialize Akavache
3. try to call BlobCache.UserAccount

### Reproduction repository

https://github.com/reactiveui/ReactiveUI

### Expected behavior

not crashing

### IDE

Visual Studio 2022

**Comment by ChrisPulman** [comment]
Hi, I am sorry to say that V9.0.1 was the last version with support for the now unsupported UWP target. Please freeze your nuget version to this version. MAUI has now replaced the older Xamarin Android, iOS, and UWP targets.

**Comment by EmilAlipiev** [comment]
Hi Chris, thanks for the information. But winui 3 will be supported using maui?

**Comment by ChrisPulman** [comment]
Yes, MAUI has support for WinUI
